spring:
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5432/fourseason?serverTimezone=Asia/Seoul
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  issuer: "s1jin-delivery"
  access-expiration: 30 # Access Token: min
  refresh-expiration: 7 # Refresh Token: day
  secret: ${JWT_SECRET}
